### ISSUE TITLE
protocol files are not available

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.db.ijba#2]
When I run the nose tests, it complains that the protocol files are not available. I assume that you forgot to put them into the repository. Please make sure that you actually have the right to re-distribute them, or update the tests.

**Comment by tiagofrepereira2012** [comment]
Just run the script below to download the data
```
./bin/bob_dbmanage.py ijba download
```
The files are too big to be shipped with the package.

**Comment by siebenkopf** [comment]
Oh, sorry, my bad. It was late yesterday. I have struggled around with my installation until I realized that #1 was my problem.

BTW: There is no documentation uploaded for this database, neither the stable nor the latest version links (badges) work.

**Comment by tiagofrepereira2012** [comment]
Hey Manuel,

There is a stable documentation (http://pythonhosted.org/bob.db.ijba/index.html), just click in the badge.
The latest is not working, I will check it out.

Cheers
