### ISSUE TITLE
Labelling the Dataset

### ISSUE THREAD

**Issue by praveenlovely** [bioidiap/bob.db.ijba#3]
Hi,

How have u labelled the dataset? The raw dataset has all the subject_IDs as 0. Though there are separate template ID and the sighting iD, how do we group the images under a subject?

**Comment by siebenkopf** [comment]
Could you please be more specific about the error that you are reporting? Is this an error of this database interface, or an error in the raw data (for which we are not responsible)?

Why do you think the raw dataset has all subject_ids being 0? In my version of the dataset, this is surely not the case. Where did you download the original dataset?

**Comment by tiagofrepereira2012** [comment]
Hey, I was in vacation last week and I'm catching up the messages now :-)

@praveenlovely, is everything clear for you?
I will close this one, but don't hesitate to reopen if you find a bug.
For questions, please use our google groups https://groups.google.com/forum/#!forum/bob-devel

Thanks
